[package]
name = "rxfetch"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.59", features = ["wrap_help", "derive"] }
nix = { version = "0.31.1", features = ["fs"] }
owo-colors = { version = "4.2.3", features = ["alloc", "supports-color"] }
sysinfo = "0.38.2"
uname = "0.1.1"
